version: '3.6'
services:
  app:
    build: .
    env_file: configuration.env
    depends_on:
      - mongodb
      - mysql
    ports:
      - '8080:8080'

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db

  grafana:
    image: grafana/grafana:8.0.2
    depends_on:
      - prometheus
    env_file: configuration.env
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - '9090:9090'

  mysql:
    image: mysql:8.0
    restart: always
    env_file: configuration.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  db: { }
  grafana_data: { }
  mysql_data: { }
